/* Generated By:JavaCC: Do not edit this line. ProgrameBrincandoTokenManager.java */
package plp.programebrincando.parser;

/** Token Manager. */
public class ProgrameBrincandoTokenManager implements ProgrameBrincandoConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 40:
         return jjStopAtPos(0, 37);
      case 41:
         return jjStopAtPos(0, 38);
      case 43:
         return jjStopAtPos(0, 15);
      case 44:
         return jjStopAtPos(0, 39);
      case 60:
         jjmatchedKind = 18;
         return jjMoveStringLiteralDfa1_0(0x100000L);
      case 61:
         return jjMoveStringLiteralDfa1_0(0x10000L);
      case 62:
         jjmatchedKind = 17;
         return jjMoveStringLiteralDfa1_0(0x80000L);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x400200L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x800000000L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x54800800L);
      case 71:
         return jjMoveStringLiteralDfa1_0(0x600000000L);
      case 74:
         return jjMoveStringLiteralDfa1_0(0x200000L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x180000040L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x1000000L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x28000000L);
      case 85:
         return jjMoveStringLiteralDfa1_0(0x1000000000L);
      case 86:
         return jjMoveStringLiteralDfa1_0(0x2000580L);
      default :
         return jjMoveNfa_0(1, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 61:
         if ((active0 & 0x10000L) != 0L)
            return jjStopAtPos(1, 16);
         else if ((active0 & 0x80000L) != 0L)
            return jjStopAtPos(1, 19);
         else if ((active0 & 0x100000L) != 0L)
            return jjStopAtPos(1, 20);
         break;
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x190000800L);
      case 69:
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x23000580L);
      case 73:
         return jjMoveStringLiteralDfa2_0(active0, 0x644800000L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000L);
      case 80:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000L);
      case 82:
         return jjMoveStringLiteralDfa2_0(active0, 0x40L);
      case 83:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000L);
      case 85:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000L);
      case 90:
         return jjMoveStringLiteralDfa2_0(active0, 0x200L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000L);
      case 67:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L);
      case 69:
         return jjMoveStringLiteralDfa3_0(active0, 0x40L);
      case 76:
         return jjMoveStringLiteralDfa3_0(active0, 0x800L);
      case 77:
         return jjMoveStringLiteralDfa3_0(active0, 0x44800000L);
      case 78:
         return jjMoveStringLiteralDfa3_0(active0, 0x20200000L);
      case 80:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000L);
      case 82:
         return jjMoveStringLiteralDfa3_0(active0, 0xf80400580L);
      case 85:
         return jjMoveStringLiteralDfa3_0(active0, 0x200L);
      case 90:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x10000000L) != 0L)
            return jjStopAtPos(3, 28);
         return jjMoveStringLiteralDfa4_0(active0, 0x7a0800000L);
      case 67:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000L);
      case 68:
         return jjMoveStringLiteralDfa4_0(active0, 0x500L);
      case 69:
         return jjMoveStringLiteralDfa4_0(active0, 0x3400000L);
      case 76:
         if ((active0 & 0x200L) != 0L)
            return jjStopAtPos(3, 9);
         break;
      case 77:
         return jjMoveStringLiteralDfa4_0(active0, 0x80L);
      case 82:
         return jjMoveStringLiteralDfa4_0(active0, 0x1004000000L);
      case 83:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000800L);
      case 84:
         return jjMoveStringLiteralDfa4_0(active0, 0x200040L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x200000L) != 0L)
            return jjStopAtPos(4, 21);
         return jjMoveStringLiteralDfa5_0(active0, 0x800000400L);
      case 67:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000000L);
      case 69:
         if ((active0 & 0x100L) != 0L)
            return jjStopAtPos(4, 8);
         else if ((active0 & 0x40000000L) != 0L)
            return jjStopAtPos(4, 30);
         return jjMoveStringLiteralDfa5_0(active0, 0x4000080L);
      case 70:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000L);
      case 78:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000L);
      case 79:
         if ((active0 & 0x40L) != 0L)
            return jjStopAtPos(4, 6);
         else if ((active0 & 0x800L) != 0L)
            return jjStopAtPos(4, 11);
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000L);
      case 80:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000L);
      case 82:
         return jjMoveStringLiteralDfa5_0(active0, 0x600000000L);
      case 83:
         if ((active0 & 0x2000000L) != 0L)
            return jjStopAtPos(4, 25);
         break;
      case 84:
         return jjMoveStringLiteralDfa5_0(active0, 0x101000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000000L);
      case 68:
         return jjMoveStringLiteralDfa6_0(active0, 0x200400400L);
      case 69:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000L);
      case 70:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000L);
      case 73:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000L);
      case 76:
         return jjMoveStringLiteralDfa6_0(active0, 0x80L);
      case 78:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000000L);
      case 80:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000L);
      case 82:
         return jjMoveStringLiteralDfa6_0(active0, 0x180800000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x400000L) != 0L)
            return jjStopAtPos(6, 22);
         return jjMoveStringLiteralDfa7_0(active0, 0x120000000L);
      case 69:
         return jjMoveStringLiteralDfa7_0(active0, 0x884800400L);
      case 72:
         return jjMoveStringLiteralDfa7_0(active0, 0x80L);
      case 73:
         return jjMoveStringLiteralDfa7_0(active0, 0x200000000L);
      case 78:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000L);
      case 82:
         if ((active0 & 0x1000000L) != 0L)
            return jjStopAtPos(6, 24);
         break;
      case 83:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000L);
      case 69:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000000000L);
      case 73:
         return jjMoveStringLiteralDfa8_0(active0, 0x400L);
      case 78:
         return jjMoveStringLiteralDfa8_0(active0, 0x80800000L);
      case 79:
         if ((active0 & 0x80L) != 0L)
            return jjStopAtPos(7, 7);
         break;
      case 81:
         return jjMoveStringLiteralDfa8_0(active0, 0x400000000L);
      case 82:
         return jjMoveStringLiteralDfa8_0(active0, 0x200000000L);
      case 83:
         if ((active0 & 0x100000000L) != 0L)
            return jjStopAtPos(7, 32);
         break;
      case 84:
         return jjMoveStringLiteralDfa8_0(active0, 0x804000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x20000000L) != 0L)
            return jjStopAtPos(8, 29);
         else if ((active0 & 0x800000000L) != 0L)
            return jjStopAtPos(8, 35);
         break;
      case 68:
         return jjMoveStringLiteralDfa9_0(active0, 0x800000L);
      case 69:
         return jjMoveStringLiteralDfa9_0(active0, 0x200000000L);
      case 73:
         return jjMoveStringLiteralDfa9_0(active0, 0x4000000L);
      case 82:
         return jjMoveStringLiteralDfa9_0(active0, 0x400L);
      case 84:
         return jjMoveStringLiteralDfa9_0(active0, 0x1080000000L);
      case 85:
         return jjMoveStringLiteralDfa9_0(active0, 0x400000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x800000L) != 0L)
            return jjStopAtPos(9, 23);
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStopAtPos(9, 36);
         break;
      case 69:
         if ((active0 & 0x80000000L) != 0L)
            return jjStopAtPos(9, 31);
         return jjMoveStringLiteralDfa10_0(active0, 0x400000000L);
      case 73:
         return jjMoveStringLiteralDfa10_0(active0, 0x200000000L);
      case 79:
         if ((active0 & 0x400L) != 0L)
            return jjStopAtPos(9, 10);
         break;
      case 82:
         if ((active0 & 0x4000000L) != 0L)
            return jjStopAtPos(9, 26);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 82:
         return jjMoveStringLiteralDfa11_0(active0, 0x400000000L);
      case 84:
         return jjMoveStringLiteralDfa11_0(active0, 0x200000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
static private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x200000000L) != 0L)
            return jjStopAtPos(11, 33);
         break;
      case 68:
         return jjMoveStringLiteralDfa12_0(active0, 0x400000000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
static private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x400000000L) != 0L)
            return jjStopAtPos(12, 34);
         break;
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 10;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 12)
                        kind = 12;
                     jjCheckNAdd(0);
                  }
                  else if (curChar == 34)
                     jjCheckNAddStates(0, 2);
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(0);
                  break;
               case 2:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 4:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 5:
                  if (curChar == 34 && kind > 14)
                     kind = 14;
                  break;
               case 6:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(3, 6);
                  break;
               case 7:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 8:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 9:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(7);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 3:
                  if (curChar == 92)
                     jjAddStates(7, 9);
                  break;
               case 4:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(0, 2);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 10 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   2, 3, 5, 2, 3, 7, 5, 4, 6, 8, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, "\120\122\105\124\117", 
"\126\105\122\115\105\114\110\117", "\126\105\122\104\105", "\101\132\125\114", 
"\126\105\122\104\101\104\105\111\122\117", "\106\101\114\123\117", null, null, null, "\53", "\75\75", "\76", "\74", 
"\76\75", "\74\75", "\112\125\116\124\101", "\101\120\122\105\116\104\101", 
"\106\111\115\101\120\122\105\116\104\101", "\122\105\120\105\124\111\122", "\126\105\132\105\123", 
"\106\111\115\122\105\120\105\124\111\122", "\123\105", "\106\101\103\101", "\123\105\116\101\117\106\101\103\101", 
"\106\111\115\123\105", "\120\101\122\101\106\122\105\116\124\105", 
"\120\101\122\101\124\122\101\123", "\107\111\122\101\122\104\111\122\105\111\124\101", 
"\107\111\122\101\122\105\123\121\125\105\122\104\101", "\103\117\122\103\101\116\105\124\101", 
"\125\123\101\122\103\101\116\105\124\101", "\50", "\51", "\54", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xffffffdfc1L, 
};
static final long[] jjtoSkip = {
   0x3eL, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[10];
static private final int[] jjstateSet = new int[20];
static protected char curChar;
/** Constructor. */
public ProgrameBrincandoTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public ProgrameBrincandoTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 10; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
